# Generated by Django 5.0.6 on 2024-07-19 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gantt", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="assignment",
            old_name="task",
            new_name="event",
        ),
        migrations.RenameField(
            model_name="dependency",
            old_name="from_task",
            new_name="from_event",
        ),
        migrations.RenameField(
            model_name="dependency",
            old_name="to_task",
            new_name="to_event",
        ),
        migrations.RemoveField(
            model_name="task",
            name="parent",
        ),
        migrations.AddField(
            model_name="task",
            name="expanded",
            field=models.BooleanField(default=False),
        ),
    ]
