# Generated by Django 5.0.6 on 2024-07-21 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gantt", "0003_task_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="percentDone",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="task",
            name="expanded",
            field=models.BooleanField(default=True),
        ),
    ]
