# Generated by Django 5.0.6 on 2024-07-30 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_alter_customuser_first_name_and_more"),
        ("gantt", "0004_task_percentdone_alter_task_expanded"),
    ]

    operations = [
        migrations.CreateModel(
            name="Journey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "assignments",
                    models.ManyToManyField(
                        related_name="journeys", to="gantt.assignment"
                    ),
                ),
                (
                    "dependencies",
                    models.ManyToManyField(
                        related_name="journeys", to="gantt.dependency"
                    ),
                ),
                (
                    "owners",
                    models.ManyToManyField(
                        related_name="journeys", to="accounts.membertable"
                    ),
                ),
                (
                    "tasks",
                    models.ManyToManyField(related_name="journeys", to="gantt.task"),
                ),
            ],
        ),
    ]
