# Generated by Django 5.0.6 on 2024-07-30 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gantt", "0005_journey"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="end_date",
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="task",
            name="start_date",
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
