# Generated by Django 5.0.6 on 2024-07-30 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gantt", "0006_task_end_date_task_start_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="manually_scheduled",
            field=models.BooleanField(default=True),
        ),
    ]
