# Generated by Django 5.0.6 on 2024-07-30 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gantt", "0007_task_manually_scheduled"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="end_date",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="task",
            name="start_date",
            field=models.CharField(default="", max_length=100),
        ),
    ]
