# Generated by Django 5.0.6 on 2024-07-31 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gantt", "0009_remove_task_end_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="start_date",
            field=models.CharField(default="2024-06-17", max_length=100),
        ),
    ]
