# Generated by Django 5.0.6 on 2024-07-31 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gantt", "0010_alter_task_start_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="manually_scheduled",
        ),
        migrations.AddField(
            model_name="task",
            name="end_date",
            field=models.CharField(default="2024-06-20", max_length=100),
        ),
    ]
