# Generated by Django 5.0.6 on 2024-07-31 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gantt", "0011_remove_task_manually_scheduled_task_end_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="end_date",
            new_name="endDate",
        ),
        migrations.RenameField(
            model_name="task",
            old_name="start_date",
            new_name="startDate",
        ),
    ]
