# Generated by Django 5.0.6 on 2024-07-31 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gantt", "0012_rename_end_date_task_enddate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="endDate",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="task",
            name="startDate",
            field=models.CharField(max_length=100),
        ),
    ]
