# Generated by Django 5.0.6 on 2024-07-31 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gantt", "0013_alter_task_enddate_alter_task_startdate"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="constraintType",
            field=models.CharField(default="test", max_length=100),
            preserve_default=False,
        ),
    ]
