# Generated by Django 5.0.6 on 2024-07-31 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gantt", "0014_task_constrainttype"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="eventColor",
            field=models.CharField(default="cyan", max_length=100),
            preserve_default=False,
        ),
    ]
