# Generated by Django 5.0.6 on 2024-07-31 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gantt", "0015_task_eventcolor"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["id"]},
        ),
    ]
