# Generated by Django 5.0.6 on 2024-07-31 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gantt", "0016_alter_task_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="status",
            field=models.CharField(default="Todo", max_length=100),
            preserve_default=False,
        ),
    ]
