# Generated by Django 5.0.6 on 2024-08-05 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gantt", "0017_task_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="eventColor",
            field=models.CharField(default="blue", max_length=100),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(default="Todo", max_length=100),
        ),
    ]
