# Generated by Django 5.0.6 on 2024-08-08 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gantt", "0018_alter_task_eventcolor_alter_task_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["unique_id"]},
        ),
        migrations.AddField(
            model_name="task",
            name="unique_id",
            field=models.CharField(default="1", max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
