# Generated by Django 5.0.6 on 2024-08-10 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gantt", "0019_alter_task_options_task_unique_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="gantt.task",
                to_field="unique_id",
            ),
        ),
        migrations.AlterField(
            model_name="dependency",
            name="from_event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dependencies_starting_here",
                to="gantt.task",
                to_field="unique_id",
            ),
        ),
        migrations.AlterField(
            model_name="dependency",
            name="to_event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dependencies_ending_here",
                to="gantt.task",
                to_field="unique_id",
            ),
        ),
    ]
