# Generated by Django 5.0.6 on 2024-08-10 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gantt", "0020_alter_assignment_event_alter_dependency_from_event_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="journey",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="from_assignments",
                to="gantt.journey",
            ),
        ),
        migrations.AddField(
            model_name="dependency",
            name="journey",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="from_dependencies",
                to="gantt.journey",
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="journey",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="from_resources",
                to="gantt.journey",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="journey",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="from_tasks",
                to="gantt.journey",
            ),
        ),
    ]
