# Generated by Django 5.0.6 on 2024-08-12 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gantt", "0022_alter_journey_owners"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="eventColor",
        ),
    ]
