# Generated by Django 5.0.6 on 2024-08-25 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gantt", "0023_remove_task_eventcolor"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="eventColor",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
