# Generated by Django 5.0.6 on 2024-09-06 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gantt", "0024_task_eventcolor"),
    ]

    operations = [
        migrations.AddField(
            model_name="journey",
            name="startDate",
            field=models.TextField(blank=True, null=True),
        ),
    ]
