# Generated by Django 5.0.6 on 2024-10-07 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gantt", "0025_journey_startdate"),
    ]

    operations = [
        migrations.AddField(
            model_name="dependency",
            name="lag",
            field=models.IntegerField(default=0),
        ),
    ]
