# Generated by Django 5.0.6 on 2024-07-04 01:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_name', models.CharField(max_length=80)),
                ('action_desc', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CarouselPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference_name', models.CharField(max_length=30)),
                ('preference_desc', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MemberTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_status', models.CharField(max_length=50)),
                ('role', models.CharField(choices=[('IP', 'Intended Parent'), ('ED', 'Egg Donor'), ('SU', 'Surrogate'), ('OT', 'Other'), ('NO', 'Undefined')], default='NO', max_length=2)),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
