# Generated by Django 5.0.6 on 2024-07-04 06:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_actiontable_carouselpreferences_membertable'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselUserReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_like_response', models.CharField(choices=[('YA', 'I like this feature'), ('NO', 'I do not like this feature'), ('UN', 'I have not clicked a button yet')], default='UN', max_length=2)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('carousel_preferences_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.carouselpreferences')),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
