# Generated by Django 5.0.6 on 2024-07-04 06:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_carouseluserreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditTableM1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('action_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.actiontable')),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
