# Generated by Django 5.0.6 on 2024-07-05 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_notifymem1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotifyMeM1',
        ),
    ]
