# Generated by Django 5.0.6 on 2024-07-05 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_delete_notifymem1'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotifyMeM1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
