# Generated by Django 5.0.6 on 2024-08-05 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_membertable_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membertable',
            name='role',
            field=models.CharField(choices=[('Intended Parent', 'Intended Parent'), ('Egg Donor', 'Egg Donor'), ('Surrogate', 'Surrogate'), ('Other', 'Other (Please specify)'), ('Undefined', 'Undefined')], default='Undefined', max_length=50),
        ),
    ]
