# Generated by Django 5.0.6 on 2024-09-03 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_membertable_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='membertable',
            name='carrying_multiples',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='membertable',
            name='current_milestone',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='membertable',
            name='different_lifestyle_carry',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='membertable',
            name='first_question',
            field=models.CharField(default='default', max_length=50),
        ),
        migrations.AddField(
            model_name='membertable',
            name='international_ip',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='membertable',
            name='milestone_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='membertable',
            name='next_milestone',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='membertable',
            name='same_sex_carry',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='membertable',
            name='second_question',
            field=models.CharField(default='default', max_length=50),
        ),
        migrations.AddField(
            model_name='membertable',
            name='stance_embryo_transfer',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='membertable',
            name='stance_termination',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='membertable',
            name='stance_vaccines',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='membertable',
            name='started_journey',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='membertable',
            name='third_question',
            field=models.CharField(default='default', max_length=50),
        ),
    ]
