# Generated by Django 5.0.6 on 2024-09-04 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_intakereferencetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='membertable',
            name='concerns',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
